version: '3.8'
services:
  web:
    build: .
    container_name: tu_exchange_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  media_files:
