# Generated by Django 4.2.29 on 2026-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='insurance_plan',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
