# Generated by Django 4.2.29 on 2026-03-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อไรเดอร์')),
                ('vehicle_type', models.CharField(default='Honda PCX-150 9999', max_length=50, verbose_name='ยานพาหนะ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
            ],
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='delivery_status',
            field=models.CharField(default='order_confirmed', max_length=20, verbose_name='สถานะการจัดส่ง'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.rider'),
        ),
    ]
