# Generated by Django 4.2.29 on 2026-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติ'), ('declined', 'ปฏิเสธ'), ('active', 'กำลังยืม'), ('returning', 'กำลังคืน'), ('returned', 'คืนแล้ว')], default='pending', max_length=10),
        ),
    ]
