# Generated by Django 4.2.29 on 2026-03-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='borrow_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='items.borrowrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewee')},
        ),
    ]
