# Generated by Django 4.2.29 on 2026-03-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_review_borrow_request_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
