# Generated by Django 6.0.3 on 2026-04-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_alter_review_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="items/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
