# Generated by Django 4.2.29 on 2026-04-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_itemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=10),
        ),
    ]
