# Generated by Django 6.0.3 on 2026-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0013_remove_borrowrequest_payment_status_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
